name: 360tracking
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.1.0
  - torchvision=0.3.0
  - cudatoolkit=10.0
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - pyyaml
  - tqdm
  - pyyaml
  - pip:
    - tensorboardX
    - easydict
    - opencv-python
